-- Cycle 4-A — Drop the single-install partial unique index.
--
-- Originally (v6b) this file CREATEd the partial unique index
-- `integrations_tenant_marketplace_key_active_unique` that enforced
-- one active install per (tenant_id, marketplace_key). Cycle 4-A makes
-- marketplace integrations multi-install (a tenant can connect two
-- Shopify stores, two Hive warehouses, etc.), so the constraint goes.
--
-- Idempotent: safe to re-run. On databases that never had the index
-- (fresh test DBs) the DROP is a no-op.
DROP INDEX IF EXISTS integrations_tenant_marketplace_key_active_unique;
